name: bump
on:
  repository_dispatch:
    types: [bump]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - run: |
          n=$(cat count.json)
          echo $((n+1)) > count.json
      - run: |
          git config user.name  bot
          git config user.email bot@example.com
          git add count.json
          git commit -m "bump"
          git push
